theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
bufferline = "multiple"
cursorline = true
mouse = false
auto-save = true
auto-format = true
color-modes = true
true-color = true
idle-timeout = 200

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = [
  "diagnostics",
  "position-percentage",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[keys.normal]
space.h = ":toggle lsp.display-inlay-hints"
space.c = "toggle_comments"
H = ":buffer-previous"
L = ":buffer-next"
X = "extend_line_above"
C-c = "copy_selection_on_prev_line"

[keys.insert]
j = { k = "normal_mode" }
k = { j = "normal_mode" }
