theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
bufferline = "multiple"
cursorline = true
mouse = false
auto-save = true
color-modes = true
true-color = true
idle-timeout = 200

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "position-percentage", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[keys.insert]
j = { k = "normal_mode" }
k = { j = "normal_mode" }
